services:
  audit:
    container_name: audit-worker
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    restart: always
    ports:
      - ${AUDIT_WORKER_PORT}:${AUDIT_WORKER_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - LOG_LEVEL=${LOG_LEVEL}
      - OTLP_ENDPOINT=${OTLP_ENDPOINT}
      - OTLP_AUTH_HEADER=${OTLP_AUTH_HEADER}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${AUDIT_WORKER_PORT}/healthz']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
