x-postgres-common: &postgres-common
  image: bitnami/postgresql
  restart: always
  healthcheck:
    test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
    interval: 10s
    timeout: 5s
    retries: 5
services:
  postgresql-master:
    <<: *postgres-common
    container_name: postgres-master
    ports:
      - '5432:5432'
    volumes:
      - master_data:/bitnami/postgresql
      #- ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=${REPLICATION_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_SHARED_PRELOAD_LIBRARIES=pgaudit, pg_stat_statements
      - POSTGRESQL_EXTRA_FLAGS=-c wal_level=logical

  postgresql-slave-1:
    <<: *postgres-common
    container_name: postgres-slave-1
    ports:
      - '5433:5432'
    depends_on:
      postgresql-master:
        condition: service_healthy
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=${REPLICATION_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_PASSWORD}
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_SHARED_PRELOAD_LIBRARIES=pgaudit, pg_stat_statements
    volumes:
      - slave_1_data:/bitnami/postgresql

  postgresql-slave-2:
    <<: *postgres-common
    container_name: postgres-slave-2
    ports:
      - '5434:5432'
    depends_on:
      postgresql-master:
        condition: service_healthy
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=${REPLICATION_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_PASSWORD}
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_SHARED_PRELOAD_LIBRARIES=pgaudit, pg_stat_statements
    volumes:
      - slave_2_data:/bitnami/postgresql

  electric:
    image: docker.io/electricsql/electric:latest
    container_name: postgres-realtime
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql-master:5432/${AUDIT_DB}?sslmode=disable
      # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
    ports:
      - "4000:3000"
    depends_on:
      postgresql-master:
        condition: service_healthy

#networks:
#  default:
#    external: true
#    name: nginx-proxy-manager_default

volumes:
  master_data:
    driver: local
  slave_1_data:
    driver: local
  slave_2_data:
    driver: local
    